In [6]:
# Karylle Marjorie O. Gealan

In [8]:
import numpy as np 

In [10]:
X=np.random.random((5,5)) # random 5x5 numbers
X_normalized=(X-np.mean(X))/np.std(X) # the formula
np.save("X_normalized.npy",X_normalized) #saving the file
X

array([[0.90413374, 0.31834373, 0.31290898, 0.33735089, 0.01996278],
       [0.35863932, 0.95753481, 0.90471708, 0.04734184, 0.35437262],
       [0.51882232, 0.86316801, 0.83658893, 0.49341418, 0.87371772],
       [0.89968898, 0.0467454 , 0.79050789, 0.80108051, 0.79612984],
       [0.96659217, 0.67607794, 0.16086869, 0.33342167, 0.45943993]])

In [12]:
X_normalized

array([[ 1.10205147, -0.78078742, -0.79825574, -0.71969485, -1.73983974],
       [-0.65126983,  1.27369252,  1.10392645, -1.65183831, -0.66498381],
       [-0.13641165,  0.97037994,  0.88494981, -0.21807817,  1.00428869],
       [ 1.08776517, -1.65375537,  0.73683668,  0.77081909,  0.75490669],
       [ 1.30280458,  0.36903738, -1.28694173, -0.7323241 , -0.32727778]])

In [14]:
np.save

<function save at 0x106d897b0>

In [17]:
import numpy as np

In [19]:
A=array=np.arange(1,101).reshape(10,10)**2 # 10x10 array of squares of integers from 1 to 100
A

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [21]:
div_by_3=A[A%3==0] # elements divisible by 3
div_by_3

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [27]:
np.save("div_by_3",div_by_3) #saving the file 

In [29]:
np.save

<function save at 0x106d897b0>