# EXPERIMENT 2: NUMERICAL PYTHON (NUMPY)
### GEALAN, Karylle Marjorie O. 

##### NORMALIZATION PROBLEM 1: Normalization is one of the most basic preprocessing techniques in data analytics. This involves centering and scaling process. Centering means subtracting the data from the mean and scaling means dividing with its standard deviation. In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X.



In [3]:
import numpy as np

In [5]:
X=np.random.random((5,5)) # random 5x5 numbers
X_normalized=(X-np.mean(X))/np.std(X) # the formula
X_normalized

array([[-0.16233822, -1.09781578,  1.41679339,  0.25181494,  0.70546758],
       [-1.1223605 ,  0.66650693, -0.62006641,  0.91233435,  1.01330892],
       [-0.86725328, -1.5176277 , -0.58221287,  0.69075864, -0.60065356],
       [ 0.22946354,  0.41537159, -1.31471394,  1.3016124 ,  1.81409884],
       [-0.76924736, -1.47452296, -1.06602905,  0.34108647,  1.43622403]])

In [7]:
np.save("X_normalized.npy",X_normalized) #saving the file 
np.save

<function save at 0x108575670>

#### DIVISIBLE BY 3 PROBLEM: Create the following 10 x 10 ndarray. Which are the squares of the first 100 positive integers.

In [10]:
A=array=np.arange(1,101).reshape(10,10)**2 # 10x10 array of squares of integers from 1 to 100
A

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [12]:
div_by_3=A[A%3==0] #elements divisible by 3
div_by_3

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])

In [14]:
np.save("div_by_3",div_by_3) #saving the file 
np.save

<function save at 0x108575670>